version: "3.3"
services:
  validator:
    build: docker
    image: validator
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: "none"
    volumes:
      - validator-log:/home/jarvis/validator/log

volumes:
  validator-log: