version: "3.8"
services:
  validator:
    build: docker
    image: validator
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: "none"
    environment:
      - LOGGING_FILE_NAME=/home/jarvis/log/validator.log
      - LOGGING_FILE_MAX_HISTORY=180
    volumes:
      - validator-log:/home/jarvis/log

volumes:
  validator-log: